version: "3.8"

services:
  app_laravel:
    build:
      context: ./laravel-docker
      dockerfile: ./docker/workspace/development/Dockerfile
      target: development
    image: laravel-docker:latest
    restart: unless-stopped
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./laravel-docker:/var/www
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-1215161}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel_network

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-1215161}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-1215161}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data: